name: pub_search
description: Search engine for pub.dev packages with autocomplete.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pub_api_client: ^2.4.0
  rive: ^0.10.2
  get_storage: ^2.1.1
  get: ^4.6.5
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/search.png
    - assets/search.gif
    - assets/search_to_cursor_animation.riv
